function Get-CCPCredential {
	<#
	.SYNOPSIS
	Use the GetPassword REST Web Service to retrieve passwords from the CyberArk AAM Central Credential Provider.

	.DESCRIPTION
	When the AAM Central Credential Provider for Windows is published via IIS and the Central
	Credential Provider Web Service, this function can be used to retrieve credentials.
	Passwords stored in the CyberArk Vault are retrieved to the Central Credential Provider, where
	they can be accessed by authorized remote applications/scripts using a web service call.

	.PARAMETER AppID
	Specifies the unique ID of the application issuing the password request.

	.PARAMETER Safe
	Specifies the name of the Safe where the password is stored.

	.PARAMETER Folder
	Specifies the name of the folder where the password is stored.

	.PARAMETER Object
	Specifies the name of the password object to retrieve.

	.PARAMETER UserName
	Defines search criteria according to the UserName account property.

	.PARAMETER Address
	Defines search criteria according to the Address account property.

	.PARAMETER Database
	Defines search criteria according to the Database account property.

	.PARAMETER PolicyID
	Defines search criteria according to the PolicyID account property.

	.PARAMETER Reason
	The reason for retrieving the password. This reason will be audited in the Credential Provider audit log

	.PARAMETER Query
	Defines a free query using account properties, including Safe, Folder and Object, separated by semicolons.
	For example: Safe=SafeName;Object=ObjectName;CustomProperty=Value
	When specified, all other search criteria (Safe/Folder/Object/UserName/Address/PolicyID/Database) are ignored
	by the Central Credential Provider, so they cannot be used with this parameter.

	.PARAMETER QueryFormat
	Defines the query format, which can optionally use regular expressions.
	Possible values are Exact or Regexp. The Central Credential Provider default is Exact.

	.PARAMETER ConnectionTimeout
	The number of seconds that the Central Credential Provider will try to retrieve the password.
	The timeout is calculated when the request is sent from the web service to the Vault and returned back
	to the web service.

	.PARAMETER FailRequestOnPasswordChange
	Return an error if the request is made while a password change process is underway.

	.PARAMETER Credential
	Specify the credentials object if OS User authentication is required for an AAM CCP Application.
	Enter a PSCredential object generated by the Get-Credential cmdlet.

	.PARAMETER UseDefaultCredentials
	Indicates that the the credentials of the current user are used for CCP OS User authentication.
	This can't be used with the Credential parameter and may not be supported on all platforms.

	.PARAMETER Certificate
	Specifies the client certificate from a local storethat is used for the AIMWebService request.
	Enter a variable that contains a certificate or a command or expression that gets the certificate.
	To find a certificate, use Get-PfxCertificate or use the Get-ChildItem cmdlet in the Certificate (Cert:) drive.

	.PARAMETER CertificateThumbPrint
	Enter the certificate thumbprint of the certificate.
	To get a certificate thumbprint, use the Get-Item or Get-ChildItem command in the PowerShell Cert: drive.

	.PARAMETER WebServiceName
	The name the CCP WebService is configured under in IIS.
	Defaults to AIMWebService

	.PARAMETER URL
	The URL for the CCP Host

	.PARAMETER SkipCertificateCheck
	Skips certificate validation checks.

	Using this parameter is not secure and is not recommended.

	This switch is only intended to be used against known hosts using a self-signed certificate for testing purposes.

	Use at your own risk.

	.PARAMETER Method
	The HTTP method used for the request. Defaults to GET.
	GET sends request parameters in the URL query string.
	POST sends request parameters as a JSON body, and requires Central Credential Provider version 14.2 or later.

	.PARAMETER AsCredential
	Outputs the username & password as a PSCredential object, instead of the result object.
	Cannot be used with AsSecureString.

	.PARAMETER AsSecureString
	Outputs the password as a SecureString, instead of the result object.
	Cannot be used with AsCredential.

	.EXAMPLE
	Get-CCPCredential -AppID PSScript -Safe PSAccounts -Object PSPlatform-AccountName -URL https://cyberark.yourcompany.com

	Uses the PSScript App ID to retrieve password for the PSPlatform-AccountName object in the PSAccounts safe from the
	https://cyberark.yourcompany.com/AIMWebService CCP Web Service.

	.EXAMPLE
	Get-CCPCredential -AppID PowerShell -Safe PSAccounts -UserName svc-psProvision -WebServiceName DevAIM -URL https://cyberark-dev.yourcompany.com

	Uses the PowerShell App ID to search for and retrieve the password for the svc-psProvision account in the PSAccounts safe
	from the https://cyberark-dev.yourcompany.com/DevAIM CCP Web Service.

	.EXAMPLE
	Get-CCPCredential -AppID PowerShell -Safe PSAccounts -UserName svc-psProvision -WebServiceName DevAIM -Method POST -URL https://cyberark-dev.yourcompany.com

	Uses the PowerShell App ID to search for and retrieve the password for the svc-psProvision account in the PSAccounts safe
	from the https://cyberark-dev.yourcompany.com/DevAIM CCP Web Service using POST method.

	.EXAMPLE
	$result = Get-CCPCredential -AppID PS -Safe PS -Object PSP-AccountName -URL https://cyberark.yourcompany.com

	$result.ToSecureString()

	Returns the password retrieved from CCP as a Secure String

	.EXAMPLE
	$result = Get-CCPCredential -AppID PS -Safe PS -Object PSP-AccountName -URL https://cyberark.yourcompany.com

	$result.ToCredential()

	Returns the username & password retrieved from CCP as a PSCredential object

	.EXAMPLE
	$credential = Get-CCPCredential -AppID PS -Safe PS -Object PSP-AccountName -URL https://cyberark.yourcompany.com -AsCredential

	Outputs the username & password retrieved from CCP as a PSCredential object

	.EXAMPLE
	Get-CCPCredential -AppID PS -Safe PS -Object PSP-AccountName -URL https://cyberark.yourcompany.com -UseDefaultCredentials

	Calls Invoke-RestMethod with the UseDefaultCredentials switch to use OS User authentication

	.EXAMPLE
	Get-CCPCredential -AppID PS -Safe PS -Object PSP-AccountName -URL https://cyberark.yourcompany.com -Credential $creds

	Calls Invoke-RestMethod with the supplied Credentials for OS User authentication

	.EXAMPLE
	Get-CCPCredential -AppID PS -Safe PS -Object PSP-AccountName -URL https://cyberark.yourcompany.com -CertificateThumbPrint $Cert_ThumbPrint

	Calls Invoke-RestMethod with the supplied Certificate thumbprint

	.EXAMPLE
	Get-CCPCredential -AppID PS -Safe PS -Object PSP-AccountName -URL https://cyberark.yourcompany.com -Certificate $Cert

	Calls Invoke-RestMethod with the supplied Certificate for Certificate authentication

	.EXAMPLE
	Get-CCPCredential -AppID PS -Query 'Safe=PS;Object=PSP-AccountName' -QueryFormat Exact -URL https://cyberark.yourcompany.com

	Uses the PS App ID to retrieve the password matching the free query for the PSP-AccountName object in the PS safe.

	.EXAMPLE
	Get-CCPCredential -AppID PS -Query 'Safe=PS;CustomFileCategoryName1=Yourcompany Data' -URL https://cyberark.yourcompany.com

	Uses the PS App ID to retrieve the password from the PS safe with a custom file category value that includes a space.

	.EXAMPLE
	Get-CCPCredential -AppID PS -Query 'Safe=PS;Object=PSP-.*' -QueryFormat Regexp -Method POST -URL https://cyberark.yourcompany.com

	Sends a regular expression query in a POST request body.
	#>

	[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingConvertToSecureStringWithPlainText', '', Justification = 'Suppress alert from ToSecureString ScriptMethod')]
	[CmdletBinding(DefaultParameterSetName = 'Default')]
	Param(
		# Unique ID of the application
		[Parameter(
			Mandatory = $true,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[Parameter(
			Mandatory = $true,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[string]
		$AppID,

		# Safe name
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[string]
		$Safe,

		# Folder name
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[string]
		$Folder,

		# Object name
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[string]
		$Object,

		# Search username
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[string]
		$UserName,

		# Search address
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[string]
		$Address,

		# Search database
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[string]
		$Database,

		# Search PolicyID
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[string]
		$PolicyID,

		# Reason to record in audit log
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[string]
		$Reason,

		# Free query of account properties
		[parameter(
			Mandatory = $true,
			ValueFromPipelinebyPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[string]
		$Query,

		# Format of free query
		[parameter(
			Mandatory = $false,
			ValueFromPipelinebyPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[ValidateSet('Exact', 'Regexp')]
		[string]
		$QueryFormat,

		# Number of seconds to try
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[int]
		$ConnectionTimeout,

		# Return an error if a password change is in progress
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[switch]
		$FailRequestOnPasswordChange,

		# Credentials to send in request to CCP
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[ValidateNotNullOrEmpty()]
		[PSCredential]
		$Credential,

		# Use current system credentials for request to CCP
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[Switch]
		$UseDefaultCredentials,

		# Use certificate to authenticate to CCP
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[X509Certificate]
		$Certificate,

		# Use certificate to authenticate to CCP
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[string]
		$CertificateThumbPrint,

		# Unique ID of the CCP webservice in IIS
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[string]
		$WebServiceName = 'AIMWebService',

		# CCP URL
		[Parameter(
			Mandatory = $true,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[Parameter(
			Mandatory = $true,
			ValueFromPipelineByPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[string]
		$URL,

		[parameter(
			Mandatory = $false,
			ValueFromPipeline = $false,
			ValueFromPipelinebyPropertyName = $true,
			ParameterSetName = 'Default'
		)]
		[parameter(
			Mandatory = $false,
			ValueFromPipeline = $false,
			ValueFromPipelinebyPropertyName = $true,
			ParameterSetName = 'Query'
		)]
		[switch]
		$SkipCertificateCheck,

		# HTTP method for request to CCP
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $false,
			ParameterSetName = 'Default'
		)]
		[Parameter(
			Mandatory = $false,
			ValueFromPipelineByPropertyName = $false,
			ParameterSetName = 'Query'
		)]
		[ValidateSet('GET', 'POST')]
		[string]
		$Method = 'GET',

		# Output PSCredential object
		[Parameter(Mandatory = $false)]
		[switch]
		$AsCredential,

		# Output password as SecureString
		[Parameter(Mandatory = $false)]
		[switch]
		$AsSecureString
	)

	Begin {

		#Collection of parameters which are to be excluded from the request
		[array]$ExcludedParameters += [System.Management.Automation.PSCmdlet]::CommonParameters
		[array]$ExcludedParameters += [System.Management.Automation.PSCmdlet]::OptionalCommonParameters
		[array]$ExcludedParameters += 'URL', 'WebServiceName', 'Credential', 'UseDefaultCredentials', 'CertificateThumbPrint', 'Certificate', 'SkipCertificateCheck', 'Method', 'AsCredential', 'AsSecureString'

		if ($AsCredential -and $AsSecureString) {
			throw 'AsCredential and AsSecureString cannot be used together.'
		}

		if ($PSEdition -ne 'Core') {

			#A SecurityProtocol of SystemDefault (0) lets Schannel negotiate the strongest protocol
			#both ends support, and is left untouched. Only a process pinned to explicit legacy
			#protocols needs TLS 1.2 adding, and it is combined with the protocols already permitted.
			$SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol

			if (([int]$SecurityProtocol -ne 0) -and
				([Net.SecurityProtocolType].GetEnumNames() -contains 'Tls12') -and
				(-not ($SecurityProtocol.HasFlag([Net.SecurityProtocolType]::Tls12)))) {

				Write-Verbose 'Adding TLS12 to Security Protocol'
				[Net.ServicePointManager]::SecurityProtocol = $SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

			}

		}

	}

	Process {

		#Collect bound request parameters, converting switches to boolean values
		$RequestParams = [ordered]@{ }
		$PSBoundParameters.keys | Where-Object { $ExcludedParameters -notcontains $_ } | ForEach-Object {

			$RequestParams[$_] = if ($PSBoundParameters[$_] -is [switch]) { $PSBoundParameters[$_].IsPresent } else { $PSBoundParameters[$_] }

		}

		$Request = @{
			'URI'             = "$($URL.TrimEnd('/'))/$WebServiceName/api/Accounts"
			'Method'          = $Method
			'ContentType'     = 'application/json'
			'ErrorAction'     = 'Stop'
			'UseBasicParsing' = $true
		}

		Switch ($Method) {

			'GET' {

				#Request parameters sent in URL query string
				$QueryString = ($RequestParams.Keys | ForEach-Object {
						"$_=$([System.Uri]::EscapeDataString($RequestParams[$_]))"
					}) -join '&'

				$Request['URI'] += "?$QueryString"

			}

			'POST' {

				#Request parameters sent in JSON body
				$Request['Body'] = $RequestParams | ConvertTo-Json

			}

		}

		# Add authentication parameters to request
		Switch ($($PSBoundParameters.keys)) {
			{ $PSItem -contains 'Credential' } { $Request['Credential'] = $Credential }
			{ $PSItem -contains 'UseDefaultCredentials' } { $Request['UseDefaultCredentials'] = $true }
			{ $PSItem -contains 'CertificateThumbPrint' } { $Request['CertificateThumbPrint'] = $CertificateThumbPrint }
			{ $PSItem -contains 'Certificate' } { $Request['Certificate'] = $Certificate }
		}

		$RestoreCertificatePolicy = $false

		#in PSCore use SkipCertificateCheck parameter
		if ($PSEdition -eq 'Core') {

			$Request.Add('SkipCertificateCheck', $SkipCertificateCheck.IsPresent)

		} elseif ($SkipCertificateCheck) {

			#Skip SSL Validation, saving previous certificate policy
			$CertificatePolicy = Skip-CertificateCheck
			$RestoreCertificatePolicy = $true

		}

		$result = $null

		Try {

			#send request
			$result = Invoke-RestMethod @Request

		} Catch {

			$ErrorRecord = $PSItem
			$ErrorMessage = $ErrorRecord.Exception.Message
			$ErrorID = $ErrorRecord.FullyQualifiedErrorId

			$err = $null

			#Only parse responses that look like JSON
			if ("$ErrorRecord".TrimStart().StartsWith('{')) {

				try {

					$err = $ErrorRecord | ConvertFrom-Json -ErrorAction Stop

				} catch {

					#Response is not valid JSON, keep original exception details
					$err = $null

				}

			}

			#CCP errors use ErrorMsg/ErrorCode, IIS/ASP.NET errors use Message
			if ($err.ErrorMsg) {
				$ErrorMessage = $err.ErrorMsg
				$ErrorID = $err.ErrorCode
			} elseif ($err.Message) {
				$ErrorMessage = $err.Message
			}

			#report the error and continue with any further pipeline input
			$PSCmdlet.WriteError(

				[System.Management.Automation.ErrorRecord]::new(

					$ErrorMessage,
					$ErrorID,
					[System.Management.Automation.ErrorCategory]::NotSpecified,
					$ErrorRecord

				)

			)

		} Finally {

			#Restore previous certificate policy
			if ($RestoreCertificatePolicy) {

				[System.Net.ServicePointManager]::CertificatePolicy = $CertificatePolicy

			}

		}

		if ($null -ne $result) {

			#Add ScriptMethod to output object to convert password to Secure String
			$result | Add-Member -MemberType ScriptMethod -Name ToSecureString -Value {

				$this.Content | ConvertTo-SecureString -AsPlainText -Force

			} -Force

			#Add ScriptMethod to output object to convert username & password to Credential Object
			$result | Add-Member -MemberType ScriptMethod -Name ToCredential -Value {

				New-Object System.Management.Automation.PSCredential($this.UserName, $this.ToSecureString())

			} -Force

			#Return the result from CCP
			if ($AsCredential) {
				$result.ToCredential()
			} elseif ($AsSecureString) {
				$result.ToSecureString()
			} else {
				$result
			}

		}

	}

	End { }

}
